### ISSUE TITLE
MacroPad I2C pinout diagram (not schematic) has wrong pinout.

### ISSUE THREAD

**Issue by derekmulcahy** [adafruit/Adafruit-MacroPad-RP2040-PCB#1]
The pinout for the I2C connector is wrong on the diagram!

The pinout order is the same as the FunHouse, from the top SCL/SDA/3.3V/GND.

**Comment by caternuson** [comment]
On the Macropad, the connector is on the front/right side of the PCB. On the FunHouse, the connector is on the back/left side of the PCB. The combination of the two makes the pads end up in the same physical arrangement when viewed in the PCB layout.

**Comment by derekmulcahy** [comment]
But this diagram gives the impression that GND is at the top of the connector, it is at the bottom.

https://github.com/adafruit/Adafruit-MacroPad-RP2040-PCB/blob/main/Adafruit%20MacroPad%20RP2040%20Pinout.pdf

It is not the schematic but the pinout diagram that is incorrect.

**Comment by caternuson** [comment]
Thanks for clarifying. That document does look incorrect.

@kattni Hey, can you take a look? Might have something to do with the "front" of the PCB actually being the "back" of the MacroPad (as used).

**Comment by dhalbert** [comment]
If I just plug in a STEMMA/QT cable to the MacroPad, it is yellow-blue-red-back top to bottom. So the diagram is upside down for that connector.

**Comment by kattni** [comment]
Thank you for catching this. The connector was reversed on the Fritzing object, which is used for the basis of the PrettyPins images. I have updated the PrettyPins images and the Fritzing object to the appropriate order.
