### ISSUE TITLE
Update schematics and board to Rev D

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit-MacroPad-RP2040-PCB#2]
A discord user asked for this, to see the revised audio amplifier.

@ladyada

**Comment by ladyada** [comment]
@BlitzCityDIY no rush, can you add?

**Comment by BlitzCityDIY** [comment]
added!

**Comment by jasonj2232** [comment]
Hi! I am the discord user who had requested for these files. I would just like to thank you all for responding so quickly and for being an awesome bunch of people! Thank you so much!
